Water Quality And Flood Control/Controllers/HomeTrialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Water_Quality_And_Flood_Control.Controllers;
using System.Diagnostics;


namespace Water_Quality_And_Flood_Control.Controllers
{
    [HandleError]
    public class HomeTrialController : Controller
    {
        

        // GET: HomeTrial
        public ActionResult Index()
        {
            return View();
        }

        // GET: AdminView
        public ActionResult AdminView()
        {
            return View();
        }

        // GET: Home Page
        public ActionResult Home()
        {
            return View();
        }

        public ActionResult MapsLeaflet()
        {
            return View();
        }

        // GET: Sensor Interface
        public ActionResult SensorInterface()
        {
            //MOCK Sensor Input. The data passes from sensor/API to controller(this) to view(SensorInterface). 
            //View Validates . 
            //If Validation successful, then data passes from view(SensorInterface) to controller(this) to database(Controller/SensorData --> SE_CodingProject).
            SensorData SensorInputInfo = new SensorData
            {
                AreaName = "Area 11",
                TimeStamp = DateTime.Now,
                Resistance = 4,
                Voltage = 4,
                Temperature = 32,
                PHValue = 7,
                DissolvedOxygen = 12,
                RadioIsotopeLevel = "R Isotope",
                StableIsotopeLevel = "S Isotope", 
                CurrentSpeed = 20,
                WaterLevel = 10
            };
            return View(SensorInputInfo);
        }

        // GET: Public User Landing Page
        public ActionResult LabGraphReportGen()
        {
            return View();
        }

        // GET: Public User Landing Page
        public ActionResult PublicUserLandingPage()
        {
            return View();
        }

        // GET: Laboratory User Landing Page
        public ActionResult LaboratoryUserLandingPage()
        {
            return View();
        }

        public ActionResult UserInterface()
        {
            return View();
        }

        // GET: PublicUser Interface
        public ActionResult PublicUser()
        {
            //MOCK Value retrival from database(/Controller/SensorData and LocationData  ---> SE_CodingProject). 
            //Data passes from database(SE_CodingProject) to controller(this) to view(PublicUser).
            SensorData PublicUserInfo = new SensorData
            {
                AreaName = "Area 21",
                TimeStamp = DateTime.Now,
                Temperature = 39,
                PHValue = 5,
                CurrentSpeed = 14,
                WaterLevel = 13
            };
            return View(PublicUserInfo);
        }

        // GET: LaboratoryUser Interface
        public ActionResult LaboratoryUser()
        {
            //MOCK Value retrival from database(/controller/SensorData ---> SE_CodingProject). 
            //Data passes from database(SE_CodingProject) to controller to view(LaboratoryUser).
            //View validates(LaboratoryUser).
            //If validation successfull, then data passes from view(LaboratoryUser) to controller(this) to database(/Controller/SensorData --> SE_CodingProject).
            SensorData LabUserInfo = new SensorData
            {
                AreaName = "Area 13",
                TimeStamp = DateTime.Now,
                Resistance = 11,
                Voltage = 19,
                Temperature = 39,
                PHValue = 5,
                DissolvedOxygen = 10,
                RadioIsotopeLevel = "R2 Isotope",
                StableIsotopeLevel = "S2 Isotope",
                CurrentSpeed = 14,
                WaterLevel = 13
            };
            return View(LabUserInfo);
        }
        
        public ActionResult drawTempGraph() //method that draws the temperature graph when called
        {
            
                var myChart = new Chart(width: 200, height: 200)
                    .AddTitle("Voltage Readings")
                      .AddSeries(
                      name: "Voltage Over Time",
                      xValue: new[] { "11/1/18 9:17:22", "11/2/18 9:18:22", "11/3/18 9:19:22", "11/4/18 14:11:22", "11/5/18 14:11:22","11/6/18 14:11:22","11/7/18 14:11:22","11/8/18 14:11:22","11/9/18 14:11:22","11/10/18 14:11:22","11/11/18 14:11:22","11/12/18 14:11:00","11/13/18 14:11:22","11/15/18 14:11:22","11/16/18 14:11:22" },
                      yValues: new[] { "39",
"33",
"31",
"40",
"36",
"35",
"35",
"31",
"39",
"33",
"39",
"39",
"38",
"36",
"31",
})
                    .Write("PNG");


                return null;
            



        }

        public ActionResult drawWaterLevelGraph()
        {
            var myChart = new Chart(width: 200, height: 200)
                    .AddTitle("Water Level Above Warning Level")
                      .AddSeries(
                      name: "Voltage Over Time",
                      xValue: new[] { "11/1/18 9:17:22", "11/2/18 9:18:22", "11/3/18 9:19:22", "11/4/18 14:11:22", "11/5/18 14:11:22", "11/6/18 14:11:22", "11/7/18 14:11:22", "11/8/18 14:11:22", "11/9/18 14:11:22", "11/10/18 14:11:22", "11/11/18 14:11:22", "11/12/18 14:11:00", "11/13/18 14:11:22", "11/15/18 14:11:22", "11/16/18 14:11:22" },
                      yValues: new[] { "16",
"20",
"9",
"1",
"13",
"13",
"14",
"17",
"17",
"5",
"16",
"10",
"16",
"20",
"9",
})
                    .Write("PNG");


            return null;
        }

        public ActionResult drawO2Graph()
        {
            var myChart = new Chart(width: 200, height: 200)
                    .AddTitle("Dissolved O2 Readings")
                      .AddSeries(
                      name: "Voltage Over Time",
                      xValue: new[] { "11/1/18 9:17:22", "11/2/18 9:18:22", "11/3/18 9:19:22", "11/4/18 14:11:22", "11/5/18 14:11:22", "11/6/18 14:11:22", "11/7/18 14:11:22", "11/8/18 14:11:22", "11/9/18 14:11:22", "11/10/18 14:11:22", "11/11/18 14:11:22", "11/12/18 14:11:00", "11/13/18 14:11:22", "11/15/18 14:11:22", "11/16/18 14:11:22" },
                      yValues: new[] { "4",
"7",
"8",
"20",
"6",
"6",
"1",
"2",
"4",
"1",
"3",
"10",
"15",
"3",
"1",
})
                    .Write("PNG");


            return null;
        }

        public ActionResult drawpHGraph()
        {
            var myChart = new Chart(width: 200, height: 200)
                    .AddTitle("pH Readings")
                      .AddSeries(
                      name: "Voltage Over Time",
                      xValue: new[] { "11/1/18 9:17:22", "11/2/18 9:18:22", "11/3/18 9:19:22", "11/4/18 14:11:22", "11/5/18 14:11:22", "11/6/18 14:11:22", "11/7/18 14:11:22", "11/8/18 14:11:22", "11/9/18 14:11:22", "11/10/18 14:11:22", "11/11/18 14:11:22", "11/12/18 14:11:00", "11/13/18 14:11:22", "11/15/18 14:11:22", "11/16/18 14:11:22" },
                      yValues: new[] { "4",
"6",
"7",
"3",
"7",
"13",
"9",
"11",
"5",
"12",
"10",
"7",
"7",
"4",
"2",
})
                    .Write("PNG");


            return null;
        }

        public ActionResult drawCurrentGraph()
        {
            var myChart = new Chart(width: 200, height: 200)
                    .AddTitle("Current Speed Readings")
                      .AddSeries(
                      name: "Voltage Over Time",
                      xValue: new[] { "11/1/18 9:17:22", "11/2/18 9:18:22", "11/3/18 9:19:22", "11/4/18 14:11:22", "11/5/18 14:11:22", "11/6/18 14:11:22", "11/7/18 14:11:22", "11/8/18 14:11:22", "11/9/18 14:11:22", "11/10/18 14:11:22", "11/11/18 14:11:22", "11/12/18 14:11:00", "11/13/18 14:11:22", "11/15/18 14:11:22", "11/16/18 14:11:22" },
                      yValues: new[] { "30",
"7",
"7",
"6",
"17",
"12",
"1",
"16",
"13",
"1",
"14",
"10",
"25",
"4",
"25"
})
                    .Write("PNG");


            return null;
        }


    }

    
}

Water Quality And Flood Control/Controllers/SensorDatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Water_Quality_And_Flood_Control.Controllers
{
    public class SensorDatasController : Controller
    {
        private WQAFDS_System db = new WQAFDS_System();

        // GET: SensorDatas
        public ActionResult Index()
        {
            return View(db.SensorDatas.ToList());
        }

        // GET: SensorDatas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SensorData sensorData = db.SensorDatas.Find(id);
            if (sensorData == null)
            {
                return HttpNotFound();
            }
            return View(sensorData);
        }

        // GET: SensorDatas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SensorDatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AreaName,TimeStamp,Resistance,Voltage,Temperature,PHValue,DissolvedOxygen,RadioIsotopeLevel,StableIsotopeLevel,CurrentSpeed,WaterLevel")] SensorData sensorData)
        {
            if (ModelState.IsValid)
            {
                db.SensorDatas.Add(sensorData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sensorData);
        }

        // GET: SensorDatas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SensorData sensorData = db.SensorDatas.Find(id);
            if (sensorData == null)
            {
                return HttpNotFound();
            }
            return View(sensorData);
        }

        // POST: SensorDatas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AreaName,TimeStamp,Resistance,Voltage,Temperature,PHValue,DissolvedOxygen,RadioIsotopeLevel,StableIsotopeLevel,CurrentSpeed,WaterLevel")] SensorData sensorData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sensorData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(sensorData);
        }

        // GET: SensorDatas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SensorData sensorData = db.SensorDatas.Find(id);
            if (sensorData == null)
            {
                return HttpNotFound();
            }
            return View(sensorData);
        }

        // POST: SensorDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SensorData sensorData = db.SensorDatas.Find(id);
            db.SensorDatas.Remove(sensorData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Water Quality And Flood Control/Controllers/UserDatasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace Water_Quality_And_Flood_Control.Controllers
{
    public class UserDatasController : Controller
    {
        private WQAFDS_System db = new WQAFDS_System();

        // GET: UserDatas
        public ActionResult Index()
        {
            return View(db.UserDatas.ToList());
        }

        // GET: UserDatas/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserData userData = db.UserDatas.Find(id);
            if (userData == null)
            {
                return HttpNotFound();
            }
            return View(userData);
        }

        // GET: UserDatas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: UserDatas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "UserName,email,number")] UserData userData)
        {
            if (ModelState.IsValid)
            {
                db.UserDatas.Add(userData);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(userData);
        }

        // GET: UserDatas/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserData userData = db.UserDatas.Find(id);
            if (userData == null)
            {
                return HttpNotFound();
            }
            return View(userData);
        }

        // POST: UserDatas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "UserName,email,number")] UserData userData)
        {
            if (ModelState.IsValid)
            {
                db.Entry(userData).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(userData);
        }

        // GET: UserDatas/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            UserData userData = db.UserDatas.Find(id);
            if (userData == null)
            {
                return HttpNotFound();
            }
            return View(userData);
        }

        // POST: UserDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            UserData userData = db.UserDatas.Find(id);
            db.UserDatas.Remove(userData);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Water Quality And Flood Control/Views/HomeTrial/AdminView.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @Html.ActionLink("Index for Sensor Data", "Index", "SensorDatas")<br />
    @Html.ActionLink("Create Record for Sensor Data", "Create", "SensorDatas")<br />
    @Html.ActionLink("Delete Record from Sensor Data", "Delete", "SensorDatas")<br />
    @Html.ActionLink("Edit Sensor Data Record", "Edit", "SensorDatas")<br />
    @Html.ActionLink("Details of Sensor Data", "Details", "SensorDatas")<br />
</div>

<div>
    @Html.ActionLink("Index for Location Data", "Index", "LocationDatas")<br />
    @Html.ActionLink("Create Record for Location Data", "Create", "LocationDatas")<br />
    @Html.ActionLink("Delete Record from Location Data", "Delete", "LocationDatas")<br />
    @Html.ActionLink("Edit Location Data", "Edit", "LocationDatas")<br />
    @Html.ActionLink("Details of Location Data", "Details", "LocationDatas")<br />
</div>

<div>
    @Html.ActionLink("Index for User Data", "Index", "UserDatas")<br />
    @Html.ActionLink("Create Record for User Data", "Create", "UserDatas")<br />
    @Html.ActionLink("Delete Record from User Data", "Delete", "UserDatas")<br />
    @Html.ActionLink("Edit User Data", "Edit", "UserDatas")<br />
    @Html.ActionLink("Details of User Data", "Details", "UserDatas")<br />
</div>

Water Quality And Flood Control/Views/HomeTrial/Home.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>Hello Homepage</div>

@{ 
    ViewBag.Title = "Home";
}

Water Quality And Flood Control/Views/HomeTrial/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@{
    ViewBag.Title = "Index Of Pages";
}

<h2>Index Of Pages</h2>

<p>Hello from our View Template!</p>

<head>
    <link rel="stylesheet" href="~/Content/leaflet.css" />
    <script src="~/Scripts/leaflet.js"></script>
    <script src="~/Scripts/Leaflet.Control.Custom.js"></script>
</head>

<style>
    #map {
        height: 600px;
    }
</style>

<div id="map">

<script>
 //   var map = L.map('map')
 //       .setView([13.7542, 100.493], 12);
//
//    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
//        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
//    }).addTo(map);
    var map = L.map('map').setView([41.881832, -87.623177], 12);

    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);

    L.control.custom({
      position: 'topright',
        content: '<button type="button" class="btn btn-default">' +
            '    <i class="fa fa-crosshairs"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-info">' +
            '    <i class="fa fa-compass"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-primary">' +
            '    <i class="fa fa-spinner fa-pulse fa-fw"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-danger">' +
            '    <i class="fa fa-times"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-success">' +
            '    <i class="fa fa-check"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-warning">' +
            '    <i class="fa fa-exclamation-triangle"></i>' +
            '</button>',
        classes: 'btn-group-vertical btn-group-sm',
        style:
        {
            margin: '10px',
            padding: '0px 0 0 0',
            cursor: 'pointer',
        },
        datas:
        {
            'foo': 'bar',
        },
        events:
        {
            click: function (data) {
                console.log('wrapper div element clicked');
                console.log(data);
            },
            dblclick: function (data) {
                console.log('wrapper div element dblclicked');
                console.log(data);
            },
            contextmenu: function (data) {
                console.log('wrapper div element contextmenu');
                console.log(data);
            },
        }
    })
        .addTo(map);
</script>
    </div>

Water Quality And Flood Control/Views/HomeTrial/LaboratoryUserLandingPage.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "LaboratoryUserLandingPage";
}
@model Water_Quality_And_Flood_Control.Controllers.LocationData

<h2>Hello Laboratory User! </h2>

<p>Please enter or select location!</p>

<head>
    <link rel="stylesheet" href="~/Content/leaflet.css" />
    <script src="~/Scripts/leaflet.js"></script>
    <script src="~/Scripts/Leaflet.Control.Custom.js"></script>
</head>

<style>
    #map {
        height: 600px;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>LocationData</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.AreaName)

    <div class="form-group">
        @Html.LabelFor(model => model.AreaName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.AreaName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AreaName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Latitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" id="coord_Lat" />
            @Html.ValidationMessageFor(model => model.Latitude, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Longitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <input type="text" id="coord_Long" />
            @Html.ValidationMessageFor(model => model.Longitude, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
</div>
}


<div id="map">

    <script>
        //   var map = L.map('map')
        //       .setView([13.7542, 100.493], 12);
        //
        //    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
        //        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        //    }).addTo(map);
        var map = L.map('map').setView([41.881832, -87.623177], 12);

        map.on('click', function (e) {
            var lat = e.latlng.lat;
            document.getElementById('coord_Lat').value = lat;
        });

        map.on('click', function (e) {
            var long = e.latlng.lng;
            document.getElementById('coord_Long').value = long;
        });

        L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            maxZoom: 19,
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
        }).addTo(map);

        L.control.custom({
            position: 'topright',
            content: '<button type="button" class="btn btn-default">' +
                '    <i class="fa fa-crosshairs"></i>' +
                '</button>' +
                '<button type="button" class="btn btn-info">' +
                '    <i class="fa fa-compass"></i>' +
                '</button>' +
                '<button type="button" class="btn btn-primary">' +
                '    <i class="fa fa-spinner fa-pulse fa-fw"></i>' +
                '</button>' +
                '<button type="button" class="btn btn-danger">' +
                '    <i class="fa fa-times"></i>' +
                '</button>' +
                '<button type="button" class="btn btn-success">' +
                '    <i class="fa fa-check"></i>' +
                '</button>' +
                '<button type="button" class="btn btn-warning">' +
                '    <i class="fa fa-exclamation-triangle"></i>' +
                '</button>',
            classes: 'btn-group-vertical btn-group-sm',
            style:
            {
                margin: '10px',
                padding: '0px 0 0 0',
                cursor: 'pointer',
            },
            datas:
            {
                'foo': 'bar',
            },
            events:
            {
                click: function (data) {
                    console.log('wrapper div element clicked');
                    console.log(data);
                },
                dblclick: function (data) {
                    console.log('wrapper div element dblclicked');
                    console.log(data);
                },
                contextmenu: function (data) {
                    console.log('wrapper div element contextmenu');
                    console.log(data);
                },
            }
        })
            .addTo(map);
    </script>
</div>

<div>

    <p></p>

    <p>@Html.ActionLink("Laboratory User", "LaboratoryUser", "HomeTrial")</p>


</div>

Water Quality And Flood Control/Views/HomeTrial/PublicUserLandingPage.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "PublicUserLandingPage";
}

<h2>Hello Public User!!</h2>

<p>Please enter or select location!</p>

<head>
    <link rel="stylesheet" href="~/Content/leaflet.css" />
    <script src="~/Scripts/leaflet.js"></script>
    <script src="~/Scripts/Leaflet.Control.Custom.js"></script>
</head>

<style>
    #map {
        height: 600px;
    }
</style>

<div id="map">

    <script>
 //   var map = L.map('map')
 //       .setView([13.7542, 100.493], 12);
//
//    L.tileLayer('http://{s}.tile.osm.org/{z}/{x}/{y}.png', {
//        attribution: '&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
//    }).addTo(map);
    var map = L.map('map').setView([41.881832, -87.623177], 12);

    L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        maxZoom: 19,
        attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>'
    }).addTo(map);

    L.control.custom({
      position: 'topright',
        content: '<button type="button" class="btn btn-default">' +
            '    <i class="fa fa-crosshairs"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-info">' +
            '    <i class="fa fa-compass"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-primary">' +
            '    <i class="fa fa-spinner fa-pulse fa-fw"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-danger">' +
            '    <i class="fa fa-times"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-success">' +
            '    <i class="fa fa-check"></i>' +
            '</button>' +
            '<button type="button" class="btn btn-warning">' +
            '    <i class="fa fa-exclamation-triangle"></i>' +
            '</button>',
        classes: 'btn-group-vertical btn-group-sm',
        style:
        {
            margin: '10px',
            padding: '0px 0 0 0',
            cursor: 'pointer',
        },
        datas:
        {
            'foo': 'bar',
        },
        events:
        {
            click: function (data) {
                console.log('wrapper div element clicked');
                console.log(data);
            },
            dblclick: function (data) {
                console.log('wrapper div element dblclicked');
                console.log(data);
            },
            contextmenu: function (data) {
                console.log('wrapper div element contextmenu');
                console.log(data);
            },
        }
    })
        .addTo(map);
    </script>
</div>

<div>

    <p></p>

    <p>@Html.ActionLink("Public User", "PublicUser", "HomeTrial")</p>


</div>

Water Quality And Flood Control/Views/HomeTrial/UserInterface.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "UserInterface";
}

<div class="container">

    <p></p>

    <p>@Html.ActionLink("Public User", "PublicUserLandingPage", "HomeTrial")</p>
    


    <p></p>

    <p>@Html.ActionLink("Laboratory User", "LaboratoryUserLandingPage", "HomeTrial")</p>


</div>